# Generated by Django 4.1.13 on 2024-05-01 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalperformance",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "HistoricalPerformance",
                "verbose_name_plural": "HistoricalPerformances",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "PurchaseOrder",
                "verbose_name_plural": "PurchaseOrders",
            },
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendores",
            },
        ),
    ]
