# Generated by Django 4.1.13 on 2024-05-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_historicalperformance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_code",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
